mn002.po:# NOTE: BB has “suspect” for okappeti, however this means rather the opposite, to “believe, hold, trust”. Cone takes this in the sense I mention. Thanks to Brahmali for pointing this out.
mn003.po:# NOTE: BB has left-over, which is a little misleading. Normally I’d use that for sesa. But here it is not necessarily the leftovers from the bowl. More likely, since, additional food has been refused, it is extra food in the offering dishes.
mn004.po:# NOTE: Note that BB renders this phrase differently here and at AN 10.99
mn005.po:# NOTE: Both MS and BB are unclear as to the speaker here. BB’s section 9 attibutes the proceeding phrases to sariputta. But surely the question is an interjection by Moggallana, as indicated by the punctuation in MS. However, to start a new speaker here, as MS does, is to suggest that this passage is spoken by Moggallana, which is surely incorrect. The close -ti in the previous segment must simply indicated a quoted term.
mn005.po:# NOTE: BB’s “son of a former cartwright” is implausible. Surely the point is that he used to be a cartwright. The idiom -putta is often disserved by rendering it as “son”; here it just means that he is “one of the cartwrights”, or “from a family of cartwrights”.
mn005.po:# NOTE: suddhā assa sāre patiṭṭhitā recurs at AN 4.190 (of an assembly) and AN 3.93 (of seeds and monks). In both cases BB has “pure, established in the core”, whereas here he has “come to consist purely of heartwood”.
mn005.po:# NOTE: BB follows PTS edition here, but MS is preferable. PTS omits the close -ti, and hence treats this sentence as a simple continuation of Moggallana’s speech. But it reads much better as an exclamation by the good monks.
mn007.po:# NOTE: BB has “liberation”, obviously following PTS in reading “mokkhasammata”. This reading is supported by MA 93, which has 度相. (The other Chinese parallel at T 51 doesn’t have a close parallel with this phrase.) However the comm evidently reads lokkha: Tattha lokkhasammatāti lūkhabhāvasammatā, lūkhabhāvanti cokkhabhāvaṃ, visuddhibhāvaṃ detīti evaṃ sammatāti vuttaṃ hoti. The problem is that lokkha gives the exact opposite sense: rough or dirty. Nor does there appear to be any supporting sense in Sanskrit. The PTS dict suggests reading cokkha=clean here: https://suttacentral.net/define/cokkha, and I think this is the best reading. Liberation doesn’t fit the imagery of the text. Nor, so far as I know, was it generally held among the brahmins that liberation came from bathing alone. On the contrary, it is precisely those brahmins who developed the notion of liberation who insisted on the inner understanding. I suspect the Chinese translation, therefore, is a normalization, as is the reading mokkha in the Pali.
mn008.po:# NOTE: This question is a little curiously phrased in the Pali, and I suspect some corruption. The idiom adimeva occurs several times in the Samyutta (SN 47.15, etc.), where it refers to a mendicant purifying the “starting point” of kusala dhamma, i.e. sila and ditthi. Since ditthi are also spoken of here, the context must be the same. Thus BB following the comm errs in inserting “meditative training” here, as this “adi” is specifically said to precede meditation, as indeed it does in this sutta. (Neither MA 91 nor EA 47.9 appears to have close parallel to this phrase) This is just the start of the comm’s systematic misinterpretation of this sutta. Further, the question must be “how” this is done, as that is the answer the Buddha gives. Both Chinese texts have 云何 here, which typically stands for katham = how?
mn011.po:# NOTE: In the parallel passage at AN 4.241 BB renders this as a quote.
mn011.po:# NOTE: The idiom “ko assaso kim balam” is found only here and at MN 93. There, it also deals with an unequivocal claim to superiority. But the brahmin avoids the question, whereas here it is answered directly. A normal sense of assaso is “confidence”. Given that the answer does, in fact, deal with confidence, it seems this is relevant here. BB’s “on the strength of what argument or what authority” doesn’t quite catch it.
mn011.po:# NOTE: Not sure why BB has “vision” here.
mn011.po:# NOTE: BB evidently takes akkhayati in the sense of “it is plain” (?) I’m not sure why, the normal sense of “it is said” works fine. It seems to be supported by the comm, and relates to the following durakkhata. The term sammaggata is apparently only found here. I think BB’s “rightly directed” is overly literal, it simply means “become right, proper or ideal”.
mn012.po:# NOTE: BB has “many hundreds of assemblies” but at AN 8.69 he changes it to “an assembly consisting of many hundreds”
mn012.po:# NOTE: BB has ’etremely", but text (here and PTS) omits ekanta.
mn012.po:# NOTE: I’m not sure that BB’s “in the crevices” here makes sense. If they’re inn a crevice, would you just step over them? At AN 10.21 the identical phrase in a different context is rendered, “let me not harm small creatures that cross my path”. It’s interesting that the thoughts of the ascetic and the lion are the same.
mn012.po:# NOTE: BB’s “make” is incorrect, there is no insinuation that they made these themselves.
mn012.po:# NOTE: I’m not convinced by BB’s “per day” here, there is no āha.
mn013.po:# NOTE: This group of three, including kāmā, rūpā (plural) and vedanā is also found at AN 3.126 and AN 10.29, where it also relates to the teachings of outsiders. In both places BB correctly translates “forms”, but here he has “material form” (singular). The simile below deals with a “lovely” woman who dies and her body decomposes. Thus it could be a simile for either sights or the body. However the fact that it is objectified as a woman’s body suggests the former; and the discussion is about the disappearance of beauty. In fact, in SN 35 and similar context, rūpa as “sights” is always plural, whereas in SN 22 it is singular (ko rūpassa adinavo …)
mn013.po:# NOTE: Surely this is the correct interpretation of ubhato byulham sangamam, as found in PTS dict, an unlike BB’s “double array”. In AN, without ubhato the same phrase is rendered by him as “fray”.
mn013.po:# NOTE: BB has “slippery” for addāvalepana. the basic meaning is “wet plaster”. While the application may indeed mean slippery, i.e. coated with something so they couldn’t be climbed, the term seems to occur in only one other passage, SN 35.243. There it is also used to signify impregnability. But rather than slipperiness, it is because the wet plaster is resistant to fire. This could equally apply in our current sutta.
mn013.po:# NOTE: Readings here are highly uncertain. BB evidently follows PTS reading pakkaṭṭhī, but see the doubts expressed by PTS dict for that word. VRI comm has Chakaṇakāyāti kuthitagomayena. Given that the parallel passage at Cnd 199 has chakaṇaṭī, it seems pakkaṭṭhī is likely a back-reading from the comm. MA 99 and T 53 have “molten copper” 融銅, while EA 21.9 has 消鐵相灑 (translated by pasadika as “molten iron” (?)). But I am not sure what these are rendering. Excrement of various sorts was commonly used to defend castles. It may well have been hot, but if we accept chakaṇakā, the text does not say hot. Abhivagga is equally obscure. Pali has it only here, and Skt only knows it in the sense of circuit, compass. Comm says “satadanta”, which is no less obscure. Does it refer to some multi-pronged weapon? Mahabharata has a śataghnī, “a stone or cylindrical piece of wood studded with iron spikes”. My sense is that if it meant something generic like BB’s “heavy weight” we would not find it used only here.
mn014.po:# NOTE: BB’s evil-doers for kururakammanta is inexact. I always coorus in the specific sense of sopmeone who follows a cruel livelihood. eg AN 4.198, AN 6.57
mn015.po:# NOTE: Anumana seems to only occur twice in the EBTs, here and SN 22.36. There, BB accepts the sense “measure against”. It seems to me this meaning applies here. the passage specifically discusses, not an inference in general, but how one is to measure oneself against another. This, of course, reads straight from the etymology of the term. Moreover, this sense makes the whole sutta hang together better. The next section refers to paccavekkhana, i.e. “reflection”. So this section is about an external standard, the next section is about an inner standard. In later texts, especially Mil 6.4.1, anumana did indeed come to mean “inference”.
mn018.po:# NOTE: In this sentence and the next, BB omits bhagava as the subject and object respectively of the sentence. Both Chalmers’ and Horner’s translations get this right. Nyanamoli’s gets the first one right, but omits the second. Thanissaro gets neither.
mn020.po:# NOTE: BB’s title is curious, given that there is nothing corresponding to “distracting”, and that saṇṭhana means “stopping, stilling”, not “removal”.
mn020.po:# NOTE: The repetitions here are dubious. PTS abbreviates heavily, while MS here and following omits the *action* that causes the thoughts to stop. BB translates as if the action were stated. I would do the same, if I were to find a witness to support it.
mn021.po:# NOTE: The grammar here is a little obscure, and the various translations evidence this. Chalmer’s is the only clearly correct one: the Buddha is applying the Golden rule, starting with the nuns, then to phagguna. Horner misses the shift in object and simply repeats verbatim. BB, following Nyanamoli, has “speaks dispraise in your presence”, without clarifying dispraise of who. But in the next passage, “you” is specified as object. In both passages, we should read tava (genitive) as playing the same role as bhikkhuninam in the former passages. The confusion comes because the genitive plays two roles in the passages, with sammukha and as the object of criticism/blows. These passages inherit tava as used in the former sense but apply it in the latter. In the next passage sammukha is omitted, presumably because it is unnecessary to specify being hit in your own presence.
mn021.po:# NOTE: I follow BB in assuming that the PTS reading, with diva, divatara, divatarayeva, is correct, even though it is not really followed consistently.
mn022.po:# NOTE: Nyanamoli/BB follow comm. in saying “killer” of vultures, but this seems unjustified. √badh clearly means “trap” a monkey at SN 47.7. This term seems simple, but strangely enough only Chalmers gets this right. Other translators prefer “trainer”, which is very odd. There seems no support for this, despite the highly obscure reference to the Indika mentioned in the note to the Rhys Davids/Oldenberg Vinaya translation here. http://www.sacred-texts.com/bud/sbe17/sbe17142.htm they say “tormentor” is more literal, but this is wrong, as we have seen, “trapper” is perfectly literal. People trap animals all the time, I don’t know why this has caused any problems.
mn022.po:# NOTE: These lines omitted without note by BB/Ny
mn022.po:# NOTE: The ceva here doesn't have an exclusive sense; see BB's article https://tricycle.org/magazine/i-teach-only-suffering-and-end-suffering/
mn024.po:# NOTE: Last phrase omitted by BB.
mn024.po:# NOTE: BB has “to be attained without these states”, but this seems to be unwarranted. I am not sure if this is just an amplification, or whether it reads the -ehi as causal. However aññatra usually takes the ablative and that is the case here. Thanissaro gets this right.
mn025.po:# NOTE: Nyanamoli/BB’s “wicker hurdles” is too clever: vakara/vagura is the same root as wicker. But it’s hardly likely that an entire area was enclosed in wicker. The normal sense is “net”, so presumably it meant nets strung on high stakes. The deer or whatever would have leap over it, thus revealing their position.
mn026.po:# NOTE: Note how text in this passage varies the verb with upasampajja: pavedeti for Alara, viharati for Gotama. Chalmers, Warren, and Horner get this right, Bodhi and Thanissaro do not. In addition, BB has “in this way” for ettavata here, which is not very accurate. But see MN 79, where we have sacchikato hissa, bhante, ettāvatā ekantasukho loko hotī in a similar context. There he has, “at this point”. Surely the two passages should be translated consistently.
mn026.po:# NOTE: The universal agreement among translators that this means “made a pact, agreed” is puzzling, unless they’re reading saññapesum; but I can’t find such a reading. Santhapeti in the sense of “stop” is well established, eg vitakkasanthana. The phrase occurs in a similar context at AN 10.93 + 94, where it refers to the noisy wanderers agreeing to stop talking. There BB renders as “silenced one another”, which is fine in context, but doesn’t necessarily apply here. The common feature of both contexts is that they stop each other (from behaving inappropriately).
mn027.po:# NOTE: BB, Thanissaro, and Horner all take “kaneruka “as” having tusks”, but this seems unjustified. If the PTS dict (following comm.) is right in saying kaneru is a “young elephant”, we can take “kaneruka” as a possessive, i.e. “she-elephant with calves”, i.e. “mature, fully-grown”, which is, in any case, implied by the context.
mn028.po:# NOTE: NOTE: Nyanamoli/BB’s “objective basis” is an unwarranted intrusion of abhidhamma ideas. This set of verbs always occur together and there is no need to treat them any other way here. arammana in the EBTs typically means something close to “meditation subject”. It’s used in the sense of the contemplative practice, relying on which, the desired outcome is achieved.
mn028.po:# NOTE: NOTE: Older translations take this in the sense “gets angry”, while BB and Thanissaro have “disturbed, agitated”. the former is unjustified as the elements are not personalized, while the latter is too weak. The term is only used, here and AN 5.197, in the sense of a sudden destructive expansion or inflation; note that the term is not used for the next passage, where there is a diminution.
mn029.po:# NOTE: The instrumental should really be “because of”, see BB’s translation of the similar idiom at AN 8.61. But as the text makes clear, the cause is not really the labha, etc., but the ayoniso manasikara that follows it. This becomes more evident in the following sections dealing with sila, etc. This, i think, justifies the oblique rendering here.
mn030.po:# NOTE: BB’s rendering (followed by Thanissaro) groups sakaya patinnaya with just the first kind of claim, but surely it should apply to all three, as in Horner. Furthermotre, it is better to translate as “do all claim direct knowledge” rather than “do all have direct knowledge, as they claim”. In DN 2 Ajita propounds the view: “natthi loke samaṇabrāhmaṇā … sayaṃ abhiññā sacchikatvā pavedenti”. Given that religious texts typically present the views of rivals in a negative light (odium theologicum) it is a good practice to translate these as sympathetically as possible, i.e. to not impute any contradictions or absurdities not clearly required by the text. Thus since at least one of these claimed that no-one had direct knowledge, it would be a direct contradiction of their own views to claim such for themselves. Given that the text allows us to translate it in a way so as to avoid such contradiction, we should choose this approach.
mn031.po:# NOTE: This idiom seems to only occur in emphatic contexts, so BB’s “why not” seems too weak.
mn031.po:# NOTE: BB has “by surmounting”, but samatikkamaya must be dative, not instrumental. samatikkamaya is regularly used in this sense, eg samatikkamaya samvattati, “leads to going beyond”.
mn032.po:# NOTE: Despite BB’s note, there is no reason to think this passage refers to the “abhidhamma”. Note that in the second part of the passage it simply refers to dhammi katha, i.e. dhamma discussion. Here, as usual in the EBTs, abhidhamma means, not “higher Dhamma “but” about the teaching”.
mn034.po:# NOTE: Following BB in reading patthetha, comm. acknowledges both readings.
mn035.po:# NOTE: This is the only use of niganthaputta. Comm says he was the son of Jain parents. From the ending of this sutta, we can see he was certainly not an ascetic, so we shouldn’t translate as “nigantha” (as per Thanissaro). On the other hand, “Nigantha’s son” (BB) is vague and liable to be misread as Mahavira’s son, or as a follower of the Jains. However, from MN 36, where Saccaka speaks critically of Mahavira and other ascetics, it is clear he is not himself a Jain. This is an interesting social example showing the fluidity of religious identity at the time. In any case, it is best to make the rendering explicit.
mn035.po:# NOTE: BB has “tank”, but udakarahada is always, so far as I can see, always used in the sense of “lake”. I don’t see any reason why such a sieve would not have been rinsed in a lake.
mn035.po:# NOTE: nibbetheti = to unravel, disentangle, clarify. BB’s “confine yourself”, by coincidence or not, is the same as Chalmers.
mn036.po:# NOTE: BB’s “in the past” is not ideal. bhutapubba always refers to specific events at a point in time (however legendary). Saying “in the past” suggests it was a general thing, which raises the question, how do they keep practicing if their heart is burst!
mn037.po:# NOTE: BB’s “endowed a hundredfold with the five kinds of heavenly music” is obscure and inaccurate. This is obviously an idiom for a divine amplification of the standard pancangika turiya, translated in AN by BB as “quintet”, which I follow.
mn037.po:# NOTE: The gods are pointing out various pretty things (idampi … idampi …) Chalmers and Horner get this right, but BB does not.
mn037.po:# NOTE: This is a surprisingly knotty idiom. Cp. SN 11.1 and 2, which also include Sakka, the word sobhati, and the idea of making merit in the past. That context draws out the slightly passive-aggressive nature of what Moggallana says here; he’s kind of praising him for having made merit, but also kind of criticizing him for living off his past. The verb sobhati in such cases is very idiomatic. Nyanatusita suggests “befits”, which apparently BB adopts in Connected Discourses. But I think the idea is that it looks nice for someone like Sakka (who is interested in such things).
mn037.po:# NOTE: BB’s “heavenly region” is incorrect. bhavana is used for the home of a divine being, eg SN 10.1, AN 6.54
mn037.po:# NOTE: BB has “attendants”, but it is feminine plural nominative, as previously.
mn037.po:# NOTE: BB’s “how much more so that …” is incorrect. Aho nuna … means “Surely that must be …”. The maidens are expressing their amazement that anyone but Moggallana might be the teacher. "We can't belive that …" is not literal, but is less confusing in English.
mn038.po:# NOTE: Readings here are problematic, and comm is no help. PTS has: “samaṇo no evamāha, samaṇā ca na ca mayaṃ evaṃ vadema”, which is followed by most translators, eg BB “The recluse says this, and so do [other] recluses, but we do not speak thus.” But I am not persuaded. The double samano/samanā idiom is odd, as is why it suddenly shifts to the negative. MS has nāma for na ca, which suggests reading samanā as ablative, paralleling the syntax of the previous section. In this case nāma becomes emphatic. Note, too, that the more common idiom is samano no garu. I think PTS is probably right in including the no here, again paralleling the previous passage. I even wonder if nāma is not a garbling of namo or some variant, paralleling garu? It is possible, of course, that na ca was normalized to nāma in MS. But in the previous passage we have satthugārave*na ca*, so it is more likely the “na ca” was inherited from there. This is not dissimilar to Thanissaro’s rendering: “The Contemplative says this. We speak thus in line with the Contemplative’s words”
mn038.po:# NOTE: BB’s “womb” here is incorrect; he fixes this in AN 3.61.
mn039.po:# NOTE: BB has “houses” but it is singular; Horner gets this right. thanissaro, in what looks like a copy paste error, has the wrong simile here.
mn040.po:# NOTE: BB’s incantations is a little harsh here. Manta in the suttas usually refers, not to magic, but to the Vedas.
mn047.po:# NOTE: BB and Horner follow comm in rendering sugata/duggata as “well behaved”. But it is not clear that it can have this sense, I cannot find any other source. Normally they mean “in a sorry state or good state”, “poor and prosperous”, eg SN 15.11, Thig 5.12, AN 5.200, DN 33. Now, out current sentence starts with “whether in a Sangha or alone”. So whoever this is talking about, it cannot refer to “practice” in the strict sense, as it must include local villagers. Of course it can still refer to general behavior. But I see no reason to depart from the normal sense. MA 186 just has a regular term for sugata here (善逝) so that is no help.
mn047.po:# NOTE: BB uses “reason” for akara in both its occurrences here. But imehi ākārehi imehi padehi imehi byañjanehi is a stock phrase, which in AN he renders “in this way, in these terms and phrases”.
mn047.po:# NOTE: The two parallels for this passage, at SN 48.42, and DN 27, both lack ayaṃ vuccati, bhikkhave, ākāravatī saddhā dassanamūlikā. Thus dalha is connected with asamhariya, contra MS text and BB’s translation, which makes better sense anyway.
mn048.po:# NOTE: Here I think the final -āya must be read as locative, as opposed to the more common dative as accepted by BB. Note that comm. here reads it as instrumental, i.e. “investigated with the knowledge of the realization of stream-entry.” The next sentence confirms that they already have stream-entry, so the dative is not appropriate.
mn049.po:# NOTE: BB’s “the state that is thus and otherwise” is unfortunate.
mn049.po:# NOTE: Following BB and CPD in reading vibhavesi. There is no need, however, to use the ca here, it answers to the ca in the last line.
mn050.po:# NOTE: vuṭṭhānima is unclear. BB has “emergence from ripening”, Chalmers has “grew and grew” (evidently reading vuddhi), Horner does not translate. Comm. has vipākavuṭṭhānavedanaṃ “feeling that emerges as a result of kamma”, which evidently underlies BB’s rendering. Given, however that the only thing we know for sure is that he has just “come out” of the Great Hell into the annex, surely it is simplest to assume that the meaning has something to do with that? This doesn’t solve the linguistic problem, but it does suggest we don’t need to seek outside the normal semantic range of vutthana.
mn050.po:# NOTE: I’m not sure why BB treats this as a metaphor, both Chalmers and Horner read it literally, and I think they were right.
mn050.po:# NOTE: Taking puth as “separate, dictinct”. I have no idea where BB/Nyanamoli get “complex, intricate rhythms” from.
mn056.po:# NOTE: BB phrases as a question, but just below the same phrase is used by Mahavira, where it is clearly not a question.
mn056.po:# NOTE: I’m not sure why BB reads “removing” for haraka. Why use ubbhata and haraka if they mean the same thing? I cannot find any references that justify PTS dict’s reading “removal” for this, i guess it is based on this passage, but elsewhere it seems to mean “carrier, deliverer” so far as i can see. But the real problem is that it ruins the metaphor. Mahavira didn’t want to blind Gotama: he thought he was already blind. He wanted to make him see properly, i.e. in line with Jainism. This simile is discussed at length in Analayo, Comparative Studies, but I do not find his arguments persuasive, as they end up making unclear metaphors.
mn056.po:# NOTE: BB’s rendering “will give delight to fools” follows the comm., but I think it misses the point of the simile. When you dye a cloth with natural dye, it will initially look fine. But the cloth must be continually pounded for the dye to settle in, otherwise it washes out quickly. That’s the point of the simile with the monkey, you can dye it, but the color will soon wash out because it can’t be fixed properly. So it will only pass a trivial inspection. I can’t make the simile work literally, so I give an interpretative translation.
mn056.po:# NOTE: sarajika parisa is translated thus by BB at SN 7.2
mn056.po:# NOTE: Reading Vessantara, as in the famous Jataka. MA 133 here has 安隱, where 隱 represents antara, and 安 may be sama. Vessa in the sense of “all” is almost unknown in Pali, and I think the unfimiliarity has led to the various readings and interpretations. the commentarial reading, which BB follows requires reading vesaman-tara, which I don’t find persuasive.
mn057.po:# NOTE: Here as throughout I agree with BB, note 634 in Connected Discourses on SN 11.11 that we should read samatta in such contexts as = samātta, i.e. a synonym to samādinna. However I just translate two terms together as “undertake”.
mn058.po:# NOTE: BB has “no one-sided answer” which is overly literal, as one-sided has a negative connotation. In AN 3.78 he renders the same phrase “Not exclusively so”, while in AN 3.21 he has “definitive declaration about this matter.” It seems to me that the point of the idiom is not that a definitive answer cannot be made, for the texts do in fact go on to do just that. Rather, it is that a proper answer is complex, and cannot be answered simply.
mn060.po:# NOTE: BB has “acts” for kar here, which is too vague. It must mean “punish”, as at AN 4.121 etc.
mn060.po:# NOTE: BB’s “definitely no immaterial realms” is surely incorrect. The abstract aruppa is never, so far as I know, used for the, but is regularly used of the meditation attainments: ye te santā vimokkhā atikkamma rūpe āruppā. Further, sabbaso does not mean “definitely”, rather it is part of the standard formula introducing the formless attainments: sabbaso rūpasaññānaṃ samatikkamā
mn062.po:# NOTE: BB translates this in line with the previous two, but in fact the syntax is the same as the next: tejo is the subject, the verb is singular, and there is no locative.
mn063.po:# NOTE: BB has “lets the surgeon pull out the arrow” which obviously makes sense, but I can’t see that it’s grammatically justified.
mn063.po:# NOTE: BB’s and PTS dict’s crossbow is probably impossible at this time. Acc. to Ven Nyanatusita, kudandaka is a pliant cane, so he suggests “cane bow or wood bow”
mn065.po:# NOTE: Comm. says raja here refers to “kings of horses”, reflected in BB’s “kingly”. But surely it is more likely this refers to the protocols of court. Rajaguna occurs in Mil 5.1.4 where it is what distinguishes royal officials from ordinary ones.
mn066.po:# NOTE: BB has the “diversity of faculties in this person”. But elsewhere when this phrase is used, it always refers to what distinguishes the spiritual development of one person as compared to another. Thus we are better taking this as a locative of reference.
mn069.po:# NOTE: BB follows PTS in having abhisamacarika here. Surely this is a confusion in the text, and the MS version is correct.
mn071.po:# NOTE: Note that while BB translates as if a pp, hence referring to historical fact, the text itself is phrased as an abstract question.
mn072.po:# NOTE: Mathita seems to only occur here in this sense. BB and Thanissaro have excogitations, which, apart from being obscure, has the wrong sense: “To consider or think (something) out carefully and thoroughly.” Horner has “supposing”, apparently taking it as a straight synonym for mannati. But at Thag 14.2 it clearly means “oppressed, weighed down”, and the same sense probably applies at Thag 1.102, too. So “burdens, anxieties, worries”.
mn074.po:# NOTE: BB has “is acceptable to me”. But this doesn’t quite work. As we see below, the problem is with dogmatic insistence. But to say something is “acceptable” is merely to not rule it out. What’s meant here is closer to the English idea of “belief”.
mn075.po:# NOTE: BB’s “surpasses” here is unjustified, and is based on the incorrect commentarial assumption. the passage is about jhana, not arahantship. The idiom samadhigayha titthati is used at Iti 23 and MN 78, where it always means “achieves the level of” or something like that.
mn075.po:# NOTE: Here dahati is better taken as “considers, takes as” rather than “burns” as per BB. Cp. SN 22.85. It’s odd that their first thought is not gratitude but revenge!
mn076.po:# NOTE: Sasakka: https://discourse.suttacentral.net/t/on-the-oddly-consequential-implications-of-the-rare-term-sasakka/4217. On anassasika, the etymology would seem to support BB’s rendering “consolation” here. But it only occurs elsewhere as a description of sankharas, where BB has “unreliable” (AN 7.66, SN 15.20, SN 22.96). In the present sutta, the focus is not that these paths do not provide emotional sustenance, but that they can’t be trusted as guides to truth. Thus “unreliable” would seem to be appropriate here, too. I am not sure how this affects the etymology.
mn076.po:# NOTE: This line is absent from the SN version of this passage. BB’s rendering no “killer, slaughterer, hearer, speaker, cognizer, intimator” is unclear if not incorrect. There are three terms, in plain and causative form. The sense of the first pair must be “kills and makes others kill”. As to the rest, the sense is clear from AN 8.16, where these are qualities of a teacher. I.e. these are ethical qualities, not merely cognitive faculties.
mn076.po:# NOTE: Bhikkhu here seems improbable. yet it is attested in the Mss, so I include it. BB omits.
mn077.po:# NOTE: Taking dhamma here in the sense of “right, true”, literally “He’s criticized with legitimate criticism”. BB has “scorned by the scorn shown to his Dhamma”. But the scorn is shown to him personally, not his Dhamma. Comm. has Dhammakkosenāti sabhāvakkosena, which seems odd to me.
mn077.po:# NOTE: alābu is botle gourd, not pumpkin, as per Nyanamoli/BB. Bottle gourd is covered in fine down, as can be seen here: https://photoplusbyritasim.files.wordpress.com/2012/07/dscf1655-400copy.jpg. There are several variant readings, and the comm/tika do not clear it up very well; I think the text is corrupt. PTS reads yattha instead of sattha, and this seems supported by tika, which has satthalūkhāni. Yaṃ yaṃ sappāyaṃ, tasseva gahaṇaṃ. Here, yam yam appears to be glossing yattha, despite the text’s reading.
mn077.po:# NOTE: The sense of yena dukkhena here was, I think, missed by previous translators, although Chalmers was closest: “when my disciples are beset by Ill, and spent with Ill in any particular shape”. Nyanamoli had “through some form of suffering”. BB has “met with suffering”. Horner omits entirely. The point is that the disciples ask about the noble truth of suffering (i.e. the abstract principle) in the case of “that dukkha because of which” (yena dukkhena, i.e. the specific instance of suffering that has affected them) they are overwhelmed. In other words, “the theoretical teaching of dukkha is one thing, but how does it help me deal with this actual suffering?” It’s a long, complex sentence, and I have broken it up and rendered it more idiomatically.
mn077.po:# NOTE: BB has “supported” for sita, which is unlikely. In cases where √sit and √baddh are found together, √sit always has the sense “attached”, eg MN 111, SN 9.2
mn078.po:# NOTE: Comm has “row” for cīra, which seems like a stretch. I can’t find it attested elsewhere in this sense. Skt dict acknowledges the sense row, line, but only in late sources, and I don’t know if it is relevant. BB renders it as “plantation”, evidently referring to the rows of trees in a plantation, though from the commentary’s description it sounds more like a decorative row or hedge. Normally it refers to strips of bark or cloth. At MN 12 we have the simile of a tindukakhanu (ebony trunk) flaking off bark (papatika). And at DN 24 we have the tindukakhāṇu-paribbājakārāmo. I suspect the usual meaning of cīra should apply, i.e. “park littered with strips of tinduka bark”, or perhaps even “the single hall, lined with strips of tinduka bark”. I am at a loss to explain the long ā in sandhi. In DN 24, perhaps also we might read “monastery built from tinduka stumps”. But tinduka is not usually used as a building material, nor is an arama a building. Regarding the numbers, the variants are 300 and 500, I have chosen the less common number.
mn078.po:# NOTE: Following BB, taking the suffix -maya in the same sense as atammaya.
mn079.po:# NOTE: BB adopts the PTS reading piti here, which is unlikely. A similar phrase recurs at MN 89 and DN 9, neither time with any variants. At MN 89 BB has “reminded him of the Blessed One”.
mn079.po:# NOTE: BB’s “dwells” for santitthati is misleading. In a parallel passage in AN 8.54 he has “associates”.
mn080.po:# NOTE: I suspect this passage is corrupt. BB’s translation is not adequate. I have translated this with reference to the gava khiram passage found at AN 5.181, etc., which is syntactically very close. One mistake in BB’s transl. is to treat the Iti as if it were part of the saying. However, from the conversation below it is clear that iti indicates he is quoting or coining a saying.
mn081.po:# NOTE: BB just has ascetic, but samanaka is always pejorative.
mn081.po:# NOTE: The description of the dish is unique, and uncertain. BB’s “rice in the sheaf”—based on comm—is hardly possible. Mudika in the sense of “soft” is the simplest reading (cf. sukaramaddava), while pandu may well refer to a yellowish colored “saffron” rice such as is common in India today.
mn081.po:# NOTE: For musala, BB has “pick”. Clearly it is a digging implement of some kind. See https://discourse.suttacentral.net/t/on-the-austerities/3837
mn081.po:# NOTE: While supeyyam might seem to mean “sauce ingredients”, and is translated as “sauce materials” by BB, it is always used in the sense of “sauce”, eg at SN 47.8. The phrase tadupiyañca sūpeyyaṃ recurs at DN 17 and SN 22.96 where it must also refer to “sauce”. This means that the food that is sent is cooked food, not, as one might assume from the quantity, dry foodstuffs. This in turn supports the rejection of paṇḍupuṭaka in the sense of “rice in the sheaf”.
mn082.po:# NOTE: BB follows comm in rendering viruparupa as “In many different ways”. However the term appears at DN 24, Ja 522, and Ja 526, where it alwyas has the meaning “disguise”.
mn083.po:# NOTE: BB has “take over the kingship” But cp DN 26, “imaṃ samuddapariyantaṃ pathaviṃ paṭipajja”, which shows rajjam must be the place here, i.e. realm.
mn083.po:# NOTE: BB omits to translate kittayamanarupa.
mn083.po:# NOTE: BB misses the plural here: the Buddha is addressing all the monks.
mn084.po:# NOTE: For orasa, BB has “offspring” here and “bosom sons” at SN 22.76 (the latter combing with putta). neither of these seem ideal; “offspring” is merely biological, while “bosom” really means “intimate”, which is not really the point. In the Sanskrit, while there are a variety of meanings, the most common and most relevant is “legitimate, rightful”. The point here is not that they are the only children of Brahma—for surely all creatures are created by Brahma—but that they are his legitimate heirs.
mn086.po:# NOTE: BB’s “attacking” seems a little excessive for kupita.
mn086.po:# NOTE: This is a difficult line. I have not traced a parallel in the Chinese versions, nor does comm or tika say anything. While obviously kilesa and variants normally refer to mental defilement, here it seems the bloody messiness of childbirth is meant. Compare, say, Snp 3.10, referring to people being immersed in blood and pus in hell, or Iti 83, where the deva’s cloths become “dirtied”. BB has “afflicted”, Thanissaro has “tormented”, and Nyanamoli had “what defilements they suffer”: but none of these capture the organic mess of it. We should not ignore the strong taboo notions around childbirth. The point here is that in samsara, birth is undergone by all beings, and the messiness of it afflicts both mother and child.
mn086.po:# NOTE: pappuyya is absolutive, not optative as per BB.
mn088.po:# NOTE: BB’s translation here is odd “only the abandoning of all unskillful states”. Elsewhere the same idiom appears (MN 15, MN 70, AN 10.55) where it rather has the sense: “the abandoning of all these (specifically aforementioned) unskillful states”
mn088.po:# NOTE: The Chinese parallel at MA 214 supports the reading chatta, i.e. umbrella 繖https://suttacentral.net/lzh/ma214/49.238. BB translates the commentary when he says “sixteen hands”. But this is impossible as it stands. 16x8 spans is only big enough for one robe, maybe a little more (Cf. pacittiya 92, where the maximum robe is 9x6 spans) But Ananda is supposed to make a whole set of three robes from this. Either a different measure is in use, or else the mention of “three” is a later addition, and originally it was meant for one robe. However the Chinese also has “three”. Regarding the rendering of bahitika, I accept the commentary’s explanation that it means “imported”. It is an unusual term, apparently only occurring here, and, as international trade was still somewhat rare in the time of the Buddha—even cloth from Kasi was regarded as special—this gives a better reason for why it is so special. This being so, there is no reason to accept the PTS dict’s explanation as “that which keeps out”, i.e. cloak. A royal cloak would likely be highly fashioned and decorated, and difficult to adapt as a monk’s robe. It makes more sense if it is simply fine imported cloth.
mn089.po:# NOTE: BB’s translation, with its exclamation marks, and Horner’s with it’s question, seem to be influenced by the commentarial background, for which see BB’s note. However, the text as it stands does not convey any outrage or emotional reaction. Karayana is simply recognizing that the kings wants to be alone, and that his duty is to stand guard by the door.
mn089.po:# NOTE: BB follows comm., which says “kularogo”, without explanation. However MA 213 has 白病, which must be from the variant paṇḍukarogino or similar.
mn090.po:# NOTE: See BB’s note. It seems to me the text is corrupt. However, despite the variants, the terms sabyabajjha and abyabajjha are well established in this exact context, and it seems to me very unlikely that “ill-will” could be meant here.
mn090.po:# NOTE: BB has “venerable sir” as vocative here, which is incorrect. Pasenadi always uses bhante as vocative, and anyway, bho doesn’t mean venerable sir. In fact, in such idioms vata bho is just an exclamation, and is frequently not used as a vocative at all.
mn091.po:# NOTE: Following BB in accepting PTS reading tayā. Curiously enough, neither MS nor PTS acknowledges the variant.
mn091.po:# NOTE: tanuka as PTS and accepted by BB hardly makes sense here.
mn092.po:# NOTE: BB has “necessary purchases and preparations”, evidently reading kaya= purchase. In this he seems to be alone. Horner has “So would you do personal service for me?”, Norman has “perform the menial duties”. Comm is silent. The context speaks of physical preparations, not purchases.
mn093.po:# NOTE: BB follows some MSS in omitting tape, but it seems to be required by the sense. It is unusual for the Buddha to refer to sila as tapas, but there you go.
mn094.po:# NOTE: BB’s “in order to learn” is not supported by comm. Nor is anuggaha used in the sense of “learn “, so far as I know, only as” support, help “. Comm: Sānuggahā vācā bhāsitā sakāraṇā vācā bhāsitā. Vuttañhetaṃ mayā ‘‘amhākaṃ kathā appamāṇaṃ, dhammova pamāṇa’’nti.” Sānuggahā vācā bhāsitā means “what was spoken was with reason. For I said that thinking:” our speech is limitless, but the teaching is limited.”
mn094.po:# NOTE: BB has “monastery”, but vihara means “dwelling” in the EBTs. Moreoever, he would hardly have built a whole monastery for one monk.
mn095.po:# NOTE: BB has “grasslands, woodlands, and waterlands” for satiṇakaṭṭhodakaṃ, but these things refer to the products, not the productive land, see AN 7.67: tiṇakaṭṭhodakaṃ sannicitaṃ. For Brahmadeyya, comm. regularly has Brahmadeyyanti seṭṭhadeyyaṃ, so “sacred grant” would seem inappropriate. also, ajjhavasati means “dwell, live”, not “rule”.
mn095.po:# NOTE: khatta in this sense only appears in this and parallel passages. BB has “minister”, but this is supported neither by Cone nor Skt.
mn095.po:# NOTE: BB has “each one of these factors”, which is incorrect. Ekamekenapi means “even a single one” see eg AN 11.16, AN 7.22, MN 85
mn095.po:# NOTE: I can’t see how BB’s “must be accomplished in the scriptures” is justified. Literally it reads: “Of Kapatika there will be talk about the scripture of the three vedas”. Sure, the future tense can, rarely, have the sense of “must be”, but there seems no call for it here. The Buddha is not recognizing Kapatika’s scholarly acumen, but the fact that the brahmins have set it up for a debate with him.
mn095.po:# NOTE: BB has: “a single teacher or a single teacher’s teacher back to the seventh generation of teachers”. But see DN 13, which clearly treats the last two clauses as separate. That this is so in the current case is confirmed by the three “-pli” s.
mn095.po:# NOTE: BB has “the ancient brahmin seers”. But brahmanānam is genitive, isayo is nominative, so it must be “seers of the brahmins”. He has corrected this at AN 5.192, but there he rather oddly has the singular: “ancient seers among the brahmin”
mn095.po:# NOTE: BB has “based on …”. But in the similar phrases at AN 4.117 and 5.114 it seems the meaning as i have given, and there BB has “things that provoke …”
mn096.po:# NOTE: For vanna here, take your pick: beauty, class, fame. Comm has class, BB has beauty. ularavanna only appears once elsewhere at DN 18, where it could mean any of these, but most likely beauty. Ulara is somewhat distantly applied to vanna as beauty also at AN 5.43. Finally, in a number of suttas we have the abstract vannata, which always seems to mean beauty.
mn097.po:# NOTE: BB has “living at the Taṇḍulapāla Gate”, DPPN has “Near the gate was the residence of the brahmin Dhānañjāni.” But it is notable that none of the usual terms for staying or residence are found here (viharati, nivesati, etc.). Nor is this place mentioned elsewhere as his residence. Now, tandula means “rice”, “pala/pali “means” guard”, and dvara is a gate or door. I think Dhananjani was an official who worked at the gate, which was a checkpoint for the movement of rice in and out of the city. It was, i suspect, in this capacity that he was able to to skim off funds.
mn097.po:# NOTE: As for karaniya katabba, this is clearly referring to the bali as at AN 4.61, AN 5.41. For the last two verbs, BB has “refreshed and nourished”. But pinetabbo is probably from pīṇa = fat, swollen, agreeing with bruheti, to increase. These terms are probably unique in this context, and contrast with the expected poseti found earlier. It speaks, I think, to Dhananjani’s sense of entitlement: he merely has to provide for his family, but he must fatten himself.
mn098.po:# NOTE: Bhunjati at MN 98 must relate to the problematic yathābhuttañca bhuñjatha in MN 129, DN 17, and DN 26. Most translators there have, implausibly, “eat”. Here, Norman has “enjoy” while BB has “govern”. But the meaning probably is similar to the archaic English form “use”, in the legal sense of “the benefit or profit of lands”. Thus yathābhuttañca bhuñjatha means “use as has been used”, i.e. “don’t increase taxes”. That fits with the context, as this passage is all about ways people earn a living.
mn100.po:# NOTE: BB omits tevijjānaṃ
mn101.po:# NOTE: BB’s translation is based on Abhidhamma via comm, and is incorrect.
mn101.po:# NOTE: BB takes viraga here in the sense of “fade away”, but it seems hard then to differentiate it from nijjinna. In addition, in the simile viraga is used in the sense of dispassion. Thus I think that is the sense here, too.
mn102.po:# NOTE: The phrasing here is a little odd. But I can't see a justification for the way BB has construed the syntax.
mn102.po:# NOTE: BB has “rushing onward” for uddham saram, while Hornner has loftily maintain attachment. But it seems to me the point is related to the common phrase uddhamsoto, i.e. heading upstream, i.e. getting reborn in a higher realm.
mn103.po:# NOTE: Var readings vacisamhara, vacisamsara, vacisankhara: Comm: Vacīsaṃhāroti vacanasañcāro. Imehi kathitaṃ amūsaṃ antaraṃ paveseyya, tumhe imehi idañcidañca vuttāti amūhi kathitaṃ imesaṃ antaraṃ paveseyyāti attho, Tika: Vacanasañcāroti pesuññavasena aññathāvacanupasaṃhāro. The parallel passage is at AN 2.63, where samsara is the MS reading, and adopted by BB there. Comm there gives a completely different explanation: ubhato vacīsaṃsāroti dvīsupi pakkhesu aññamaññaṃ akkosanapaccakkosanavasena saṃsaramānā vācā vacīsaṃsāro. Tika has: Saṃsaramānāti pavattamānā. Despite this, I think the reading samhara makes better sense, as per MN comm.
mn105.po:# NOTE: The reading is problematic, and BB follows several manuscripts in omitting āneñjasaṃyojanena hi kho visaṃyutto. However, as the MS notes, it is commented on: Āneñjasaṃyojanena hi kho visaṃyuttoti āneñjasamāpattisaṃyojanena visaṃsaṭṭho. But the idea that such a person is genuinely detached from the anenja cannot be right. I suspect there was an old confused reading, and that this line connects back to the immediately prior anenjapatisamyutta. i.e. they’re not detached from the “fetter” of the anenja, but from “what is connected with” the anenja, i.e. the talk, etc. as discussed earlier.
mn105.po:# NOTE: Here and below, the verb echoes the simile, a connection missed in BB.
mn105.po:# NOTE: See BB’s note on why anupa-is to be preferred here. See also Analayo, Comparative Study, p 611 note 136 “SHT IV 500 folio 3V 3 reads [sā]va[ś]eṣaṃ nira[va](śe)ṣaṃ (iti manyamānaḥ); cf. also SHT X 3274V 3”
mn106.po:# NOTE: balalapana is found at Thig 5.2 of a beautiful body, and at SN 22.95 we have balalapini, where BB has “beguiler of fools” noting that the comm says this refers to vinnana, although this doesn’t seem completely certain. At Ja 421 we have of kama: Ahahā bālalapanā, “Oh, oh, the cries of fools.” I think this context gives a good idea, it means something like “cooed over by fools”, or in the case of lapini, clumsily: “causing fools to coo over it.”
mn108.po:# NOTE: BB reads this following PTS, with the following passage a continuation by Vassakara. But that means there is no response by the general. Surely it reads better as in MS edition. Note that just below, taggha starts a new speaker.
mn110.po:# NOTE: See my note on AN 10.62 for this usage. Also, note that while PTS dict does not have bhatti in this sense, it surely, being from bhajati, has the same sense as asappurisasevana here. BB also translates thus.
mn114.po:# NOTE: I am not really sure of the force of this statement. Following comm., BB translates as “conduct is either the one or the other”, which to my mind is overburdening the text. It turns the statement into a strong affirmation of an ethical dualism, something that is avoided or outright repudiated elsewhere. Given that this passage appears to have no parallels, I would be reluctant to follow such a reading unless it was unavoidable.
mn114.po:# NOTE: apariniṭṭhitabhāva is found only here, see BB’s note. At Thig 13.2 parinitthita means “prepared” food, and I follow that for lack of anything else.
mn116.po:# NOTE: Not sure why BB takes these as descriptions of Bharadvaja, it sounds unlikely that a paccekabuddha would be described as “beautiful, with crested mane”! Comm is silent here, which I take as endorsing the default, i.e. a straight list of names.
mn122.po:# NOTE: here and at MN 137 BB translates vokkamma as “err and turn aside”. But the use at DN 29 shows that it can apply to someone who truns aside from a bad teaching and should be praised for it.
mn124.po:# NOTE: Here BB has “worn a robe”, but this seems to be a mistake, as it is not found in the PTS either. it was probably copied carelessly from the dharema here.
mn124.po:# NOTE: I think this is the right meaning, as opposed to BB’s “working on robes”. Cp. Pc 46
mn125.po:# NOTE: The parallel passage occurs at MN 125 and AN 2.38. MS text has kāmamajjhāvasati at AN 2.38 and kāmamajjhe vasanto at MN 125. BB has “living in the midst of sensual pleasures” at MN 125 and “dwells in sensual pleasures” at AN 2.38, with the note: “I follow Ce and Be kāmamajjhāvasati (= kāmaṃ ajjhāvasati), as against Ee kāmamajjhe vasati.” Notably, the first two terms in the sequence are reversed. the sequence in MN 125 makes better sense: it starts with where they live, what they do, what they think about, and gradually moves up to being consumed and seeking more. I take this as the correct sense and translate both passages accordingly.
mn125.po:# NOTE: See note by BB, and Analayo’s discussion in Comparative Studies. Manuscripts, including Skt and Chinese, seem to vary between kayupasamhita … dhammupasamhita, and kamupasamhita. Evidently the entire passage is corrupt, and I don’t see that a definitive conclusion is attainable. It seems to me the simplest explanation of the situation in the Pali text is that the above fragment on giving up the five hindrances was accidentally added as part of the abbreviated gradual training section. With that removed, kamupasamhita becomes the more obvious reading here.
mn127.po:# NOTE: BB has “puntually, but pageva usually means” how much more so", and here it also has tara.
mn127.po:# NOTE: BB has “By reason of the factor [responsible for rebirth]” for tadangena, but it is an idiom that appears in AN 9.33 without causal implication. If the answer was in terms of cause, the next question would not be necessary.
mn129.po:# NOTE: BB omits this portion.
mn129.po:# NOTE: See BB’s note on the negative. However, it seems to me there is no need to supply it. In this first case, the discussion is simply about what is and is not appropriate, and it makes sense for either the good or bad person to say that such things are found in them. In the next case, the acts are explicitly bad, so the negative sense, as found in the ext, is required.
mn129.po:# NOTE: Bhunjati at MN 98 must relate to the problematic yathābhuttañca bhuñjatha in MN 129, DN 17, and DN 26. Most translators have, implausibly, “eat”. At MN 98, Norman has “enjoy” while BB has “govern”. But the meaning probably is similar to the archaic English form “use”, in the legal sense of “the benefit or profit of lands”. Thus yathābhuttañca bhuñjatha means “use as has been used”, i.e. “don’t increase taxes”.
mn131.po:# NOTE: The ca here indicates that this phrase belongs with the previous padas. BB’s translation following the comm tortures the grammar.
mn135.po:# NOTE: Note that here BB uses the masculine, even though the text specified man or woman.
mn136.po:# NOTE: This specific phrasing is shared with MN 136 and AN 6.62. In both cases, the context follows a case where a junior monk has made a silly statement. I think the phrasing is meant to express a certain frustration, if I may dare to use such a term of the Buddha! The parsing of vibhajantassa is problematic, see BB’s note on AN 6.62.
mn138.po:# NOTE: text has upekkha in the first case, upekkhasukha subsequently, with apparently no vll. because of the way he abbreviates, BB’s translation doesn’t show this difference.
mn144.po:# NOTE: the variant spellings between MN and SN seem irreconcilable. I follow BB in CDB, which is also accepted by Malalasekera in DPPN.
mn150.po:# NOTE: BB’s “now righteously, now unrighteously” is incorrect: cp SN 1.7, etc.
